<?php

namespace AppBundle\Repository;

/**
 * CategoriaPersonaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriaPersonaRepository extends \Doctrine\ORM\EntityRepository
{
}
