<?php

namespace AppBundle\Repository;

/**
 * CiudadaniaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CiudadaniaRepository extends \Doctrine\ORM\EntityRepository
{
}
