<?php

namespace AppBundle\Repository;

use AppBundle\Entity\FormatoProyecto;

/**
 * FormatoProyectoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormatoProyectoRepository extends \Doctrine\ORM\EntityRepository
{
    public function agregarFormato($data)
    {
        try{
            $em = $this->getEntityManager();
            $formato = new FormatoProyecto();
            $formato->setNombre($data['nombre']);

            $em->persist($formato);
            $em->flush();
            $msg = $formato;

        }catch (\Exception $e)
        {
            if(strpos($e->getMessage() , 'Duplicate entry') > 0)
            {
                $msg = 'El formato ya existe, no se puede agregar';
            }
            else
            {
                $msg = 'Se produjo un error al insertar el formato';
            }
        }
        return $msg;
    }

    public function modificarFormato($data)
    {
        try
        {
            $em = $this->getEntityManager();
            $formato = $em->getRepository('AppBundle:FormatoProyecto')->find($data['idFormato']);

            if (!empty($formato)) {
                $formato->setNombre($data['nombre']);
                $em->flush();
                $msg = $formato;
            } else {
                $msg = $formato;
            }

        }catch (\Exception $e)
        {
            $msg = 'Se produjo un error al modificar el formato';
        }

        return $msg;
    }

    public function eliminarFormato($id)
    {
        try
        {
            $em = $this->getEntityManager();
            $formato = $em->getRepository('AppBundle:FormatoProyecto')->find($id);

            if (!empty($formato)) {
                $em->remove($formato);
                $em->flush();
                $msg = $formato;
            } else {
                $msg = $formato;
            }

        } catch (\Exception $e) {

            if (strpos($e->getMessage(), 'foreign key') > 0) {
                $msg = 'Existen proyectos asociados a este formato, no se puede eliminar';
            } else {
                $msg = 'Se produjo un error al eliminar el formato';
            }
        }
        return $msg;
    }

}
