<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Profesion;

/**
 * ProfesionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfesionRepository extends \Doctrine\ORM\EntityRepository
{
    public function agregarProfesion($data)
    {
        try{
            $em = $this->getEntityManager();
            $profesion = new Profesion();
            $profesion->setNombre($data['nombre']);

            $em->persist($profesion);
            $em->flush();
            $msg = $profesion;

        }catch (\Exception $e)
        {
            if(strpos($e->getMessage() , 'Duplicate entry') > 0)
            {
                $msg = 'La profesión ya existe, no se puede agregar';
            }
            else
            {
                $msg = 'Se produjo un error al insertar la profesión';
            }
        }
        return $msg;
    }

    public function modificarProfesion($data)
    {
        try
        {
            $em = $this->getEntityManager();
            $profesion = $em->getRepository('AppBundle:Profesion')->find($data['idProfesion']);

            if (!empty($profesion)) {
                $profesion->setNombre($data['nombre']);
                $em->flush();
                $msg = $profesion;
            } else {
                $msg = $profesion;
            }

        }catch (\Exception $e)
        {
            $msg = 'Se produjo un error al modificar la profesión';
        }

        return $msg;
    }

    public function eliminarProfesion($id)
    {
        try
        {
            $em = $this->getEntityManager();
            $profesion = $em->getRepository('AppBundle:Profesion')->find($id);

            if (!empty($profesion)) {
                $em->remove($profesion);
                $em->flush();
                $msg = $profesion;
            } else {
                $msg = $profesion;
            }

        } catch (\Exception $e) {

            if (strpos($e->getMessage(), 'foreign key') > 0) {
                $msg = 'Existen personas asociadas a esta profesión, no se puede eliminar';
            } else {
                $msg = 'Se produjo un error al eliminar la profesión';
            }
        }
        return $msg;
    }
}
