<?php

namespace AppBundle\Repository;

/**
 * ProyectoEmpresaReporteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProyectoEmpresaReporteRepository extends \Doctrine\ORM\EntityRepository
{
}
