<?php

namespace AppBundle\Repository;

/**
 * ProyectoPersonaReporteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProyectoPersonaReporteRepository extends \Doctrine\ORM\EntityRepository
{
    public function totalPresupuestoPagadoReportado($idProyecto)
    {
        $em = $this->getEntityManager();

        $dql = 'SELECT SUM(p.presupuestoACobrar) as totalACobrar
                FROM AppBundle:ProyectoPersonaReporte p
                JOIN p.reporte r
                JOIN r.proyecto e
                WHERE e.id =:p1';

        $query = $em->createQuery($dql);
        $query->setParameter('p1', $idProyecto);

        $total = $query->getResult();

        return $total[0]['totalACobrar'];

    }

    public function totalPresupuestoPorPagarReportado($idProyecto)
    {
        $em = $this->getEntityManager();

        $dql = 'SELECT sum(p.presupuestoRestante) as totalAPagar
                FROM AppBundle:ProyectoPersonaReporte p
                JOIN p.reporte r
                JOIN r.proyecto e
                WHERE e.id =:p1';

        $query = $em->createQuery($dql);
        $query->setParameter('p1', $idProyecto);

        $total = $query->getResult();

        if ($total[0]['totalAPagar'] == 0) {
            $dql = 'SELECT sum(p.presupuestoRestante) as totalAPagar
                    FROM AppBundle:ProyectoPersonaCargo p
                    JOIN p.proyecto e
                    WHERE e.id =:p1';

            $query = $em->createQuery($dql);
            $query->setParameter('p1', $idProyecto);

            $total = $query->getResult();
        }

        return $total[0]['totalAPagar'];

    }

}
