<?php

namespace AppBundle\Repository;

/**
 * ProyectoPersonaCargoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProyectoPersonaCargoRepository extends \Doctrine\ORM\EntityRepository
{
    public function totalPresupuestoPagado()
    {
        $em = $this->getEntityManager();

        $dql = 'SELECT SUM(p.presupuestoACobrar) as totalACobrar
                FROM AppBundle:ProyectoPersonaReporte p';

        $query = $em->createQuery($dql);

        $total = $query->getResult();

        return $total[0]['totalACobrar'];

    }

    public function totalPresupuestoPorPagar()
    {
        $em = $this->getEntityManager();

        $dql = 'SELECT sum(p.presupuestoRestante) as totalAPagar
                FROM AppBundle:ProyectoPersonaCargo p';

        $query = $em->createQuery($dql);

        $total = $query->getResult();

        return $total[0]['totalAPagar'];

    }

    public function graficoTotalesCargosContratos()
    {
        $em = $this->getEntityManager();

        $dql = 'SELECT c.nombre, COUNT(e) as cant
                FROM AppBundle:ProyectoPersonaCargo e
                JOIN e.cargo c
                GROUP BY c.nombre
                ORDER BY cant DESC';

        $query = $em->createQuery($dql);

        return $query->getResult();

    }

    public function conceptosPersona($ci,$idProyecto)
    {
        $em = $this->getEntityManager();

        $dql = 'SELECT e.noContrato, c.nombre as cargo, e.presupuestoCargo
                FROM AppBundle:ProyectoPersonaCargo e
                JOIN e.cargo c with c.id  not in (1,5,25)
                JOIN e.persona p
                JOIN e.proyecto f
                WHERE p.carnetIdentidad =:p1
                AND f.id =:p2';

        $query = $em->createQuery($dql);
        $query->setParameter('p1', $ci);
        $query->setParameter('p2', $idProyecto);

        return $query->getResult();

    }

}
