<?php

namespace AppBundle\Repository;

use AppBundle\Entity\TipoContrato;
use AppBundle\Entity\TipoProyecto;

/**
 * TipoContratoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoContratoRepository extends \Doctrine\ORM\EntityRepository
{
    public function agregarTipoContrato($data)
    {
        try{
            $em = $this->getEntityManager();
            $tipoContrato = new TipoContrato();
            $tipoContrato->setNombre($data['nombre']);

            $em->persist($tipoContrato);
            $em->flush();
            $msg = $tipoContrato;

        }catch (\Exception $e)
        {
            if(strpos($e->getMessage() , 'Duplicate entry') > 0)
            {
                $msg = 'El tipo de contrato ya existe, no se puede agregar';
            }
            else
            {
                $msg = 'Se produjo un error al insertar el tipo de contrato';
            }
        }
        return $msg;
    }

    public function modificarTipoContrato($data)
    {
        try
        {
            $em = $this->getEntityManager();
            $tipoContrato = $em->getRepository('AppBundle:TipoContrato')->find($data['idTipoContrato']);

            if (!empty($tipoContrato)) {
                $tipoContrato->setNombre($data['nombre']);
                $em->flush();
                $msg = $tipoContrato;
            } else {
                $msg = $tipoContrato;
            }

        }catch (\Exception $e)
        {
            $msg = 'Se produjo un error al modificar el tipo de contrato';
        }

        return $msg;
    }

    public function eliminarTipoContrato($id)
    {
        try
        {
            $em = $this->getEntityManager();
            $tipoContrato = $em->getRepository('AppBundle:TipoContrato')->find($id);

            if (!empty($tipoContrato)) {
                $em->remove($tipoContrato);
                $em->flush();
                $msg = $tipoContrato;
            } else {
                $msg = $tipoContrato;
            }

        } catch (\Exception $e) {

            if (strpos($e->getMessage(), 'foreign key') > 0) {
                $msg = 'Existen conceptos asociados a este tipo de contrato, no se puede eliminar';
            } else {
                $msg = 'Se produjo un error al eliminar el tipo de contrato';
            }
        }
        return $msg;
    }

}
