<?php

namespace AppBundle\Repository;

use AppBundle\Entity\TipoProyecto;

/**
 * TipoProyectoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoProyectoRepository extends \Doctrine\ORM\EntityRepository
{
    public function agregarTipo($data)
    {
        try{
            $em = $this->getEntityManager();
            $tipo = new TipoProyecto();
            $tipo->setNombre($data['nombre']);

            $em->persist($tipo);
            $em->flush();
            $msg = $tipo;

        }catch (\Exception $e)
        {
            if(strpos($e->getMessage() , 'Duplicate entry') > 0)
            {
                $msg = 'El tipo de proyecto ya existe, no se puede agregar';
            }
            else
            {
                $msg = 'Se produjo un error al insertar el tipo de proyecto';
            }
        }
        return $msg;
    }

    public function modificarTipo($data)
    {
        try
        {
            $em = $this->getEntityManager();
            $tipo = $em->getRepository('AppBundle:TipoProyecto')->find($data['idTipo']);

            if (!empty($tipo)) {
                $tipo->setNombre($data['nombre']);
                $em->flush();
                $msg = $tipo;
            } else {
                $msg = $tipo;
            }

        }catch (\Exception $e)
        {
            $msg = 'Se produjo un error al modificar el tipo de proyecto';
        }

        return $msg;
    }

    public function eliminarTipo($id)
    {
        try
        {
            $em = $this->getEntityManager();
            $tipo = $em->getRepository('AppBundle:TipoProyecto')->find($id);

            if (!empty($tipo)) {
                $em->remove($tipo);
                $em->flush();
                $msg = $tipo;
            } else {
                $msg = $tipo;
            }

        } catch (\Exception $e) {

            if (strpos($e->getMessage(), 'foreign key') > 0) {
                $msg = 'Existen programas asociados a esta tipo de proyecto, no se puede eliminar';
            } else {
                $msg = 'Se produjo un error al eliminar el tipo de proyecto';
            }
        }
        return $msg;
    }

}
