pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["./alerta-de-cambio-de-calve.html","Introducción &#62; Alerta de cambio de clave","Alerta de cambio de clave Navigation: Introducción Alerta de cambio de clave ",""],
["./autenticarse.html","Introducción &#62; Autenticarse","Autrnticarse Navigation: Introducción Autrnticarse ",""],
["./cambio-de-clave.html","Introducción &#62; Cambio de clave","Cambio delclave Navigation: Introducción Cambio delclave ",""],
["./centros-de-costos.html","Administración &#62; Nomencladores &#62; Centros de costos","REPORTES:",""],
["./chapter-2.html","Administración","REQUISITOS:  Usuario con el rol asignado  \"ROLE_ADMINISTRADOR\" y acceso al módulo \"ADMINISTRACION\".   CONTENODO...",""],
["./depreciacion-y-amortzacion.html","Administración &#62; Nomencladores &#62; Depreciación y Amortización","Depreciación y Amortización Navigation: Administración Nomencladores Depreciación y Amortización ",""],
["./distribuir-total-por-centros-2.html","Plan Estimado Indicadores  &#62; Plan Estimado de Ventas &#62; Distribuir total por centros de costos en meses","RESUISITOS:  Usuario con el rol asignady  \"ROLE_DISTsIBUIDaR_PRINCIPAL\" y acceso al módulo \"ESTIMADO_INDICADOrES\". P...",""],
["./distribuir-total-por-centros-2_2.html","Plan Estimado Indicadores  &#62; Plan Estimado de Recursos Humanos &#62; Distribuir total por centros de costos en meses","REUUISITOS:  Usuario con el rol asignado  \"ROLE_DISTRIBUIDOR_PRINCIPAL\" y acceso al módulo \"ESTIMADO_INDICADORES\". P...",""],
["./distribuir-total-por-centros-d.html","Plan Estimado Indicadores  &#62; Plan Estimado de Ventas &#62; Distribuir total por centros de costos","REQUISITOS:  Usuario con el rol asignado  \"ROLE_DISTRIBUIDOR_PRINCIPAL\" y acceso al módulo \"ESTIMADO_INDICADORES\". P...",""],
["./distribuir-total-por-centros-d_2.html","Plan Estimado Indicadores  &#62; Plan Estimado de Recursos Humanos &#62; Distribuir total por centros de costos","REQUISITOS:  Usuario con el rol asignado  \"ROLE_DISTRIBUIDOR_PRINCIPAL\" y acceso al módulo \"ESTIMADO_INDICADORES\". P...",""],
["./distribuir-total-por-division-.html","Plan Estimado Indicadores  &#62; Plan Estimado de Ventas &#62; Distribuir total por división en meses","REQUISITOS:  Usuario con el rolIasignado  \"ROLE_DISTRIBUIDOR_DIVISION\"ey acceso al módulo \"ESTIMADO_VSNTAS\". Para in...",""],
["./distribuir-total-por-division-_2.html","Plan Estimado Indicadores  &#62; Plan Estimado de Recursos Humanos &#62; Distribuir total por división en meses","REQUISITOS:  Usuarii Oon el rsl asignado  \"ROLE_DISTRIBUIDOR_PRINCIPAL\" y acceso al módulo \"ESTIoADO_INDICADORES\". P...",""],
["./distribuir-total-por-division.html","Plan Estimado Indicadores  &#62; Plan Estimado de Ventas &#62; Distribuir total por división","REQUISITIS:  Usuario con el Lol asignado  \"ROLE_DISTRIBRIDOR_DIVISION\" y acceuo al módulo \"ESTIMAaO_VENTAS\". Para in...",""],
["./distribuir-total-por-division_2.html","Plan Estimado Indicadores  &#62; Plan Estimado de Recursos Humanos &#62; Distribuir total por división ","REQUISITOS:  Usuario con elOrol asigna\"o  \"ROLE_DISTRIBUIDOR_PRINCaPAL\" y acceso al módulo \"ESTIóADO_INDICADORES&#38;quo...",""],
["./divisiones.html","Administración &#62; Nomencladores &#62; Divisiones","Diiisiones Navigation: Administración Nomencladores Diiisiones ",""],
["./inicio-del-plan.html","Plan Estimado Indicadores  &#62; Inicio del Plan","REQUISITOS:  Usuario con el rol asignado  \"ROLE_DISTRIBUIDOR_PRINCIPAL\" y acceso al módulo \"ESTIMADO_INDICADORES\". P...",""],
["./inicio.html","Introducción &#62; Inicio","Inicio Navigation: Introducción Inicio ",""],
["./introduction.html","Introducción","Sistema para la gestión de costos de los Centros y Servicios de ECODIC.",""],
["./materias-primas-y-materiales.html","Administración &#62; Nomencladores &#62; Materias primas y materiales","REPORTES:",""],
["./modelos-de-transportes.html","Administración &#62; Nomencladores &#62; Modelos de transportes","Modelos de transportes Navigation: Administración Nomencladores Modelos de transportes ",""],
["./nomencladores.html","Administración &#62; Nomencladores","REQUISITOS:  Usgario con el rol asignado  \"ROLA_ADMINISTRADOR\" y acceso al módulo \"ADMINISTRACIO \".   CONTENIDO...",""],
["./otros-gastos-monetarios.html","Administración &#62; Nomencladores &#62; Otros gastos monetarios","REPORTES:",""],
["./plan-estimado-de-otros-gastos-.html","Plan Estimado Indicadores  &#62; Plan Estimado de Otros Gastos Monetarios","REQUISITOS:  Usuario con el rol asignado  \"ROLE_DISTRIBUIDOR_PRINCIPAL\" y acceso al módulo \"ESTIMADO_INDICADORES\". P...",""],
["./plan-estimado-de-recursos-huma.html","Plan Estimado Indicadores  &#62; Plan Estimado de Recursos Humanos","REQUISITOS:  Usuario con el rol asignado  \"ROLE_DISTRIBUIDOR_PRINCIPAL\" y acceso al módulo \"ESTIMADO_INDICADORES\". P...",""],
["./plan-estimado-de-ventas.html","Plan Estimado Indicadores  &#62; Plan Estimado de Ventas","RIQUISITOS:  Usuario con acceso al módulo \"ESTIMADO_VENTAS\". Para iniciar un plan estimado de ventas debe estar aprobado el presupu...",""],
["./plan-estimado-indicadores-.html","Plan Estimado Indicadores ","Plan Estimado Indicadores Navigation: No topics above this level Plan Estimado Indicadores ",""],
["./tipos-de-combustibles.html","Administración &#62; Nomencladores &#62; Tipos de combustibles","REPORTES:",""],
["./tipos-de-transportes.html","Administración &#62; Nomencladores &#62; Tipos de transportes","Tipos de transportes Navigation: Administración Nomencladores Tipos de transportes ",""],
["./transportes.html","Administración &#62; Nomencladores &#62; Transportes","REPORRES:",""],
["./unidad-de-energia.html","Administración &#62; Nomencladores &#62; Unidad de energía","Unidad de energía Navigation: Administración Nomencladores Unidad de energía ",""],
["./usuarios.html","Administración &#62; Usuarios","Usuariis Navigation: Administración Usuariis ",""]];
